# 00_pytorch_fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


# Introduction to Tensors

# Creating Tensors


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX=torch.tensor([[7,8],[9,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 12]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
# Tensor

TENSOR=torch.tensor([[[1,2,3],[5,6,7],[7,8,9]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 7],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

#Random Tensors


In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2443, 0.8876, 0.1953, 0.4003],
        [0.4891, 0.5366, 0.1525, 0.0716],
        [0.6582, 0.8057, 0.8757, 0.7537]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#ZEROES AND ONES

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones * random_tensor

tensor([[0.2443, 0.8876, 0.1953, 0.4003],
        [0.4891, 0.5366, 0.1525, 0.0716],
        [0.6582, 0.8057, 0.8757, 0.7537]])

In [ ]:
ones.dtype

torch.float32

# creating range of tensors and tensor-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPES




In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

dtype----> what datatype is the tensor (eg. float32 or float16)

device----> what device is your tensor on

requires_grad----> whether or not to track gradients with this tensor operation




In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor =  torch.tensor([3,6,8],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

#Getting information from tensors 
(TENSOR ATTRIBUTES)
1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'

2. Tensors not right shape - to get shape from a tensor can use 'tensor.shape'

3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
# some_tensor = float_32_tensor.type(torch.float16)

In [ ]:
# To find out details about the tensor
print(some_tensor)
print(f"Datatype of tensor; {some_tensor.dtype}")

tensor([[0.9397, 0.0781, 0.0752, 0.2772],
        [0.8135, 0.8588, 0.9465, 0.1782],
        [0.6585, 0.3049, 0.7734, 0.6480]])
Datatype of tensor; torch.float32


In [ ]:
print(f"Shape of tensor; {some_tensor.shape}")

Shape of tensor; torch.Size([3, 4])


In [ ]:
print(f"Device of tensor; {some_tensor.device}")

Device of tensor; cpu


Manupilating Tensors
( TENSORS OPERATIONS)


Tensors operations include :

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication


In [ ]:
# createa tensor and add 10

tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#for multiply by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# by reassigning the tensor
tensor = tensor * 5

In [ ]:
tensor #it changes from [1,2,3] to [5,10,15]

tensor([ 5, 10, 15])

In [ ]:
# for subtraction

tensor -2

tensor([ 3,  8, 13])

Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning are :

1. Elements-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplication needs to be satisfied

1. The inner dimensions must match:
* (3,2) @ (3,2) won't work
* (3,2) @ (2,3) will work
* (2,3) @ (3,2) will work

2. The resulting matrix has the shape of the outer dimensions
* (2,3) @ (3,2) -> (2,2) 2 x 2 matrix as result 
* (3,2) @ (2,3) -> (3,3) 3 x 3 matrix as a result

In [ ]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.1292, 0.3083, 0.4175],
        [0.2259, 0.6940, 0.7905],
        [0.1587, 0.7257, 0.6487]])

In [ ]:
tensor

tensor([ 5, 10, 15])

In [ ]:
# Element wise

tensor * tensor

tensor([ 25, 100, 225])

In [ ]:
print(tensor,'*',tensor)

tensor([ 5, 10, 15]) * tensor([ 5, 10, 15])


In [ ]:
print(f"equals : {tensor * tensor}")

equals : tensor([ 25, 100, 225])


In [ ]:
# matrix multiplication

torch.matmul(tensor,tensor)

tensor(350)

In [ ]:
tensor

tensor([ 5, 10, 15])

In [ ]:
# matrix multiplication by hand 

5*5 + 10*10 + 15*15 

350

In [ ]:
%%time 

value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(350)
CPU times: user 3.1 ms, sys: 16 µs, total: 3.12 ms
Wall time: 3.8 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.33 ms, sys: 0 ns, total: 1.33 ms
Wall time: 3.56 ms


tensor(350)

One of the most common errors in deep learning : shape errors

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

# Here instead of torch.matmul we can also use torch.mm

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we ca manipulate the shape of one of our tensors using a transpose.

A transpose switches the axis of the dimensions of the given tensor

In [ ]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [ ]:
tensor_B.T  

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Finding the min, max , mean , sum , etc 
TENSOR AGGREGATES

In [ ]:
# create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean

# NOTE -> the torch.mean() function requires a tensor of float32 
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum

torch.sum(x),x.sum()

(tensor(450), tensor(450))

 Finding the positional min and max of tensors



In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin() # finds the position in tensor that has the minimum value and returns t the index position of target value

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()

x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

Reshaping , stacking, squeezing and unsqueezing tensors

* Reshaping -> reshapes an input tensor to defined shape

* View -> Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking -> Combine multiple tensor on top of each other (vstack) or side by side (hstack)

* Squeeze -> removes all 1 dimensions from a tensor

* unsqueeze -> add a 1 dimension to a target tensor

* permute  -> Return a view of input with dimension permuted (swapped) in a certain way

In [ ]:
import torch 
x=torch.arange(1.,10.)

In [ ]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension 
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because view of a tensor shares same memory as that of original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Squeeze --> removes all single dimensions froma a taregt tensor

print(f"Previous tensor : {x_reshaped}")
print(f"Previous tensor shape : {x_reshaped.shape}")


# remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()

print(f"Previous tensor : {x_squeezed}")
print(f"Previous tensor shape : {x_squeezed.shape}")


Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor shape : torch.Size([1, 9])
Previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous tensor shape : torch.Size([9])


In [ ]:
# unsqueeze --> adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#Permute --> rearranges the dimension of a target tensor ina a specified order

x_original = torch.rand(size=(224,224,3)) # height, width, colour channels


#for perumuting the tensor to rearrange the axis or dimension order

x_permuted=x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


 INDEXING (SELECTING DATA FROM TENSORS)

 

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# lets index on new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on the middle bracket ( dim=1)

x[0,0]

tensor([1, 2, 3])

In [ ]:
# lets index on the most inner bracket (last dimension)

x[0,2,2]

tensor(9)

In [ ]:
# you can also use ":" to select all of a target dimension

x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of 0 dimension but only 1 value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
#index on x to return 3,6,9
x[:,2,2]

tensor([9])

 PYTORCH AND NUMPY

 Numpy is a popular scientific python numerical computing library and because of this, pyTorch has functionality to interact with it.

 * Data in Numpy, want in pyTorch tensor -> torch.from_numpy(ndarray)

 * pyTorch tensor -> Numpy -> torch.Tensor.numpy()


In [ ]:
#numpy array to tensor

import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor


# NOTE---> When converting from numpy to pytorch, pytorch reflects numpy's default datatype of float 64 unless specified

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# change the value of array, what will this do to tensor?

array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# from tensor to numpy

tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# change the tensor, what will happen to numpy

tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

 Reproducibility 

 Trying to take random out of random

 * In short how a neural network learns ⁉

 --> Start with random numbers -> tensor operation -> update the number to try and make them better representations of data -> again -> again .....

 * To reduce the randomness in neural networks and pyTorch comes the concept of a Random Seed

 Essentially what the random sead does is flavour of the randomness

In [ ]:
import torch

# create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0362, 0.5467, 0.0326, 0.3256],
        [0.9579, 0.4772, 0.5963, 0.9926],
        [0.0837, 0.6885, 0.0095, 0.6810]])
tensor([[0.2043, 0.0466, 0.9874, 0.0109],
        [0.9215, 0.6288, 0.2052, 0.9778],
        [0.0373, 0.0094, 0.0013, 0.6032]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random but reproducible tensors

import torch

# set the random seed

RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and pyTorch objects on the GPU's 

Making them faster computations

GPU =  faster computation on numbers
thanking to CUDA + NVIDIA hardware + pyTorch working behind the scenes to make everything hunky


* Getting a GPU

1. Use Google colab for a free GPU 
2. use your own GPU 
3. use cloud computing like AWS, Azure 


In [1]:
# check for GPU with pyTorch

import torch
torch.cuda.is_available()

True

In [2]:
# setup devoce agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
!nvidia-smi


Fri Apr  7 19:01:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
# count the number of devices

torch.cuda.device_count()

1

In [6]:
# Create a tensor (default on CPU)

tensor = torch.tensor([1,2,3],device = "cpu")

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
# move back to CPU

# if tensor is on GPU, can't transform it to numpy

tensor_on_gpu.numpy()

TypeError: ignored

In [9]:
# to fix the GPU tensor with numpy, we can first set it to CPU

tensor_back_on_cpu =  tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])